version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3
  kubernetes: circleci/kubernetes@0.4.0
  aws-eks: circleci/aws-eks@1.1.0
   
    
jobs:
  create-jayita-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - checkout
      - aws-eks/install-aws-iam-authenticator:
          release-tag: ''
      - run:
          name: Install the eksctl tool
          command: |
            if which eksctl > /dev/null; then
            echo "eksctl is already installed"
            exit 0
            fi
            mkdir -p eksctl_download
            curl --silent --location --retry 5 "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C eksctl_download
            chmod +x eksctl_download/eksctl
            SUDO=""
            if [ $(id -u) -ne 0 ] && which sudo > /dev/null ; then
            SUDO="sudo"
            fi
            $SUDO mv eksctl_download/eksctl /usr/local/bin/
            rmdir eksctl_download
      - aws-eks/create-cluster:
          cluster-name: << parameters.cluster-name >>
          skip-kubectl-install: false
          verbose: 3
          node-type: t2.large
          nodes-max: 2
          ssh-access: false
          ssh-public-key: ''
  lint:
    docker:
      - image: circleci/python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv devops
            source devops/bin/activate
            make install
            
      - run:
          name: run lint
          command: |
            source devops/bin/activate
            make lint
  
          no_output_timeout: 30m 
          
  configure-image:
    machine: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Build, Test and Upload docker image
          command: |
            docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PWD}
            docker build -t jayita19/project6:2.0 .
            docker run -d --rm --name flaskapp -p 8081:8080 jayita19/project6:2.0
            sleep 5
            docker container ls
            export URL="http://localhost:8081"
            export response=$(curl -s $URL)
            echo "This is response $response"
            if [[ $response == *"Jayita"* ]]; then
              docker stop flaskapp
            else
              docker stop flaskapp
              exit 1
            fi
            docker push jayita19/project6:2.0
            
  test-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          name: Kube cluster
          command: |
            kubectl get services
            
            
  create-deployment:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: deployment.yml
          resource-name: deployment/jayita-capstone-deployment
          
          
  test-deployment:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          name: Kube cluster
          command: |
            kubectl get svc
            kubectl get nodes
            kubectl get deployment
            kubectl get pods
            
          
workflows:
  default:
    jobs:
      - lint
      - configure-image:
          requires:
            - lint
#      - create-jayita-cluster:
#          cluster-name: jayita-capstone
#          requires:
#            - configure-image
#      - test-cluster:
#          cluster-name: jayita-capstone
#          requires:
#            - create-jayita-cluster
      - test-cluster:
          cluster-name: jayita-capstone
          requires:
            - configure-image
      - create-deployment:
            cluster-name: jayita-capstone
            requires:
              - test-cluster
      - test-deployment:
          cluster-name: jayita-capstone
          requires:
            - create-deployment              
      - aws-eks/update-container-image:
          cluster-name: jayita-capstone
          container-image-updates: 'jayita-capstone-deployment=jayita19/project6:2.0'
          get-rollout-status: true
          record: true
          requires:
           - test-deployment
          resource-name: deployment/jayita-capstone-deployment        
          
            
            
#      - aws-eks/delete-cluster:
#          cluster-name: jayita-capstone
#          requires:
#           - aws-eks/update-container-image
#
