version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3
  kubernetes: circleci/kubernetes@0.12.0
  aws-eks: circleci/aws-eks@1.1.0
  
  
jobs:
  lint:
    docker:
      - image: circleci/python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv devops
            source devops/bin/activate
            make install
            
      - run:
          name: run lint
          command: |
            source devops/bin/activate
            make lint
  
          no_output_timeout: 30m 
          
  configure-image:
    machine: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Build, Test and Upload docker image
          command: |
            docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PWD}
            docker build -t jayita19/project6:2.0 .
            docker run -d --rm --name flaskapp -p 8081:8080 jayita19/project6:2.0
            sleep 5
            docker container ls
            export URL="http://localhost:8081"
            export response=$(curl -s $URL)
            echo "This is response $response"
            if [[ $response == *"Jayita"* ]]; then
              docker stop flaskapp
            else
              docker stop flaskapp
              exit 1
            fi
            docker push jayita19/project6:2.0
            
  test-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          name: Kube cluster
          command: |
            kubectl get services
            
            
  create-deployment:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: deployment.yml
          resource-name: deployment/jayita-capstone-deployment
          
          
  test-deployment:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          name: Kube cluster
          command: |
            kubectl get svc
            kubectl get nodes
            kubectl get deployment
            kubectl get pods
            
          
workflows:
  default:
    jobs:
      - lint
      - configure-image:
          requires:
            - lint
      - aws-eks/create-cluster:
          cluster-name: jayita-capstone
          requires:
            - configure-image
      - test-cluster:
          cluster-name: jayita-capstone
          requires:
            - aws-eks/create-cluster
#      - test-cluster:
#          cluster-name: jayita-capstone
#          requires:
 #           - configure-image
      - create-deployment:
            cluster-name: jayita-capstone
            requires:
              - test-cluster
      - test-deployment:
          cluster-name: jayita-capstone
          requires:
            - create-deployment              
      - aws-eks/update-container-image:
          cluster-name: jayita-capstone
          container-image-updates: 'jayita-capstone-deployment=jayita19/project6:2.0'
          get-rollout-status: true
          record: true
          requires:
           - test-deployment
          resource-name: deployment/jayita-capstone-deployment        
          
            
            
#      - aws-eks/delete-cluster:
#          cluster-name: jayita-capstone
#          requires:
#           - aws-eks/update-container-image
#
